[package]
name = "pingrs"
version = "0.1.0"
edition = "2024"
authors = ["Sivaprakash P"]
repository = "https://github.com/sivaprakashkrp/pingrs"
license = "GPL-2.0-or-later"
description = "A TUI file explorer written in RUST with Ratatui"
readme = "README.md"
homepage = "https://github.com/sivaprakashkrp/pingrs"
keywords = ["ping", "network", "cli", "rust"]
categories = ["command-line-utilities", "os"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
colored = "3.1.1"
ping-rs = "0.1.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"